version: "3.3"

services:
  db:
    user: root
    image: mysql:5.7
    volumes:
      - database_pcc:/var/lib/mysql
    restart: always
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: somewordpress
      MYSQL_DATABASE: pcc
      MYSQL_USER: wordpress
      MYSQL_PASSWORD: wordpress

  wordpress:
    user: root
    depends_on:
      - db
    image: wordpress:latest
    ports:
      - "80:80"
    restart: always
    environment:
      WORDPRESS_DB_HOST: db:3306
      WORDPRESS_DB_USER: wordpress
      WORDPRESS_DB_PASSWORD: wordpress
      WORDPRESS_DB_NAME: pcc
    volumes:
      - ./wp-content/themes:/var/www/html/wp-content/themes
      # - ./wp-content/plugins:/var/www/html/wp-content/plugins
      - ./wp-content/uploads:/var/www/html/wp-content/uploads
    # - ./themes:/var/www/html/wp-content/themes
volumes:
  database_pcc: {}
